### ISSUE TITLE
webui slash (/) instead of colon (:) after IP address

### ISSUE THREAD

**Issue by josst10** [MisterCalvin/supermicro-java-ikvm#4]
The webui has an extra slash before the port number (http://192.168.50.7/5800), ending in a '404 not found' error. I'm using unraid and my code is below. 

Thanks!

version: "3"
services:
  1U:
    image: ghcr.io/mistercalvin/supermicro-java-ikvm:latest
    container_name: 1U
    environment:
      TZ: UTC
      USER_ID: 1000
      GROUP_ID: 1000
      KVM_HOST: 192.168.50.5
      KVM_USER: ADMIN
      KVM_PASS: ADMIN
      DISPLAY_WIDTH: 1024 # Display Width
      DISPLAY_HEIGHT: 768 # Display Height
    ports:
      - "5800:5800" # Web UI Port
      - "5900:5900" # VNC Port
    networks:
      - anjo
    volumes:
      - /mnt/user/isos:/app/vmedia/ # Virtual Media ISO's
      - /mnt/user/appdata/1U-ipmi/screenshots:/app/screenshots/ # Screenshots / Recordings
      - 1U:/config/ # Persistent Configuration for user preferences
    restart: no

volumes:
  1U:
    name: 1U

networks:
  anjo:
    driver: bridge

**Comment by MisterCalvin** [comment]
Have you tried removing the slash and adding a colon? Try accessing the container's address and port in an Incognito / Private Browsing window to ensure this isn't cache related:

http://192.168.50.7:5800
