### ISSUE TITLE
Issue connecting to IPMI "[app         ] connect failed sd:22"

### ISSUE THREAD

**Issue by 46cv8** [MisterCalvin/supermicro-java-ikvm#6]
Hey great tool, I was really hoping it would help me get into the IPMI for my server unfortunately something seems very off.
I'm wondering if perhaps the board is so old the encryption is failing with some strange error.
I ran your debug version "ghcr.io/mistercalvin/supermicro-java-ikvm:x86-1.0.1_debug" with "-e CONTAINER_DEBUG=1"

It spit out the following.
```
[supervisor  ] starting service 'app'...
[supervisor  ] started service 'app'.
[app         ] + cat /etc/cont-env.d/KVM_JAR_FILE
[app         ] + cat /etc/cont-env.d/KVM_JAR_APPCLASS
[app         ] + cat /etc/cont-env.d/KVM_EPHEMERAL_USERNAME
[app         ] + cat /etc/cont-env.d/KVM_EPHEMERAL_PASSWORD
[app         ] + cat /etc/cont-env.d/KVM_LAUNCH_ARGUMENTS
[app         ] + exec java -Djava.util.prefs.systemRoot=/config/xdg/config -Djava.util.prefs.userRoot=/config/xdg/config -Duser.home=/app -Djava.library.path=/config/xdg/cache -cp /config/xdg/cache/iKVM__V1.69.38.0x0.jar tw.com.aten.ikvm.KVMMain 192.168.xx.yyy redacted12345 redacted12345 null 63630 63631 2 0 1 5900 623
[app         ] connect failed sd:22
```

So it was able to log into the web interface and get the correct ephemeral password and username as far as I can tell.
Is there anyway to get additional logging to see what might be wrong with the "app" causing "connect failed sd:22".

Just to be clear IPMIView20 no longer works either, and the web interface on my old windows PC has stopped working too.
I suspect it may be certificate related as the stunnel logs from the old windows PC showed a bunch of errors about bad certificates that I couldn't bypass.

**Comment by 46cv8** [comment]
Good news, I rebooted my server and now your tool works fine :) Also IPMIView under windows works again too.
It's possible that it wasn't allowing iKVM due to the fact it was hung on the "Press F1 to continue due to error during boot" screen.
Although I'm not sure if normally that prevents iKVM access or not.

**Comment by MisterCalvin** [comment]
Great news! I was actually in the middle of updating the container to output more verbose debug logs (since other users are also having issues). I'm glad you got this working, if it locks up again in the future (or if anyone else has a similar issue) you can try the following from the README:

>Selecting Español or Korean from Options > Preference > Language Setting will cause a crash, and any attempts to reconnect to the Java viewer will fail. To fix this, login to your server's web interface, then navigate to Maintenance > iKVM Reset. If this does not work you can also reboot the IPMI unit by navigating to Maintenance > Unit Reset.

This will not reset the server itself, it will only reboot the IPMI unit, so it is safe to do while the server is running.

**Comment by 46cv8** [comment]
Awesome! I had no idea you could reboot the IPMI without rebooting the server. Great tip "Maintenance > Unit Reset." Thanks!

**Comment by 46cv8** [comment]
BTW! Thanks for making this awesome tool I forgot to express my huge appreciation. The number of windows VM's I've spun up in desperation to get access to iKVM is almost comical at this point.
